# Generated by Django 5.2.10 on 2026-01-18 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='random_test_min_score',
            field=models.IntegerField(default=60, verbose_name='Random test minimal ball %'),
        ),
        migrations.AddField(
            model_name='subject',
            name='random_test_question_count',
            field=models.IntegerField(default=20, verbose_name='Random test savollar soni'),
        ),
        migrations.AddField(
            model_name='test',
            name='min_score_to_unlock',
            field=models.IntegerField(default=80, verbose_name='Keyingi test uchun minimal ball %'),
        ),
        migrations.AddField(
            model_name='usertestattempt',
            name='is_random',
            field=models.BooleanField(default=False, verbose_name='Random test'),
        ),
        migrations.AlterField(
            model_name='usertestattempt',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='test_app.test'),
        ),
        migrations.AlterUniqueTogether(
            name='test',
            unique_together={('subject', 'order')},
        ),
    ]
