# Generated by Django 5.2.10 on 2026-01-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_create_sample_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_text_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Javob matni'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_text_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Javob matni'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_text_uz',
            field=models.CharField(max_length=500, null=True, verbose_name='Javob matni'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text_en',
            field=models.TextField(null=True, verbose_name='Savol matni'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text_ru',
            field=models.TextField(null=True, verbose_name='Savol matni'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text_uz',
            field=models.TextField(null=True, verbose_name='Savol matni'),
        ),
        migrations.AddField(
            model_name='subject',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='subject',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='subject',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Fan nomi'),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Fan nomi'),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Fan nomi'),
        ),
        migrations.AddField(
            model_name='test',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Test nomi'),
        ),
        migrations.AddField(
            model_name='test',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Test nomi'),
        ),
        migrations.AddField(
            model_name='test',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Test nomi'),
        ),
    ]
